### ISSUE TITLE
Missing verification: sum leaf of BTC not greater than merkle root BTC

### ISSUE THREAD

**Issue by pedr0-fr** [silversixpence-crypto/merkletree-verify#2]
I have read the documentation on this repository, [binance PoR page](https://www.binance.com/en/proof-of-reserves), [binance FAQ](https://www.binance.com/en/support/faq/frequently-asked-questions-on-mazars-verification-of-proof-of-reserves-88260dc7aab44da2a183c9a0c9abed64) and [merkle tree verification guide](https://www.binance.com/en/support/faq/how-to-verify-your-merkle-tree-information-on-a-third-party-auditor-platform-589594aedf414413bc6ba1191fd99bf4); and I understand that I can verify that my binance account was included in the merkle tree. However, there seems to be missing information to verify that the the sum of BTC of all leaves is not greater than the reported 575,742.4228 BTC of the merkle root. The BTC total of each merkle leaf should be made public so that users can verify that each parent leaf contains the BTC sum of the child leaves.

**Comment by Tolyo1234** [comment]
48b9dbbcedb1bcf596996b16f1f75136467be4f3054895505d73844b5f9a1efa

**Comment by silversixpence-crypto** [comment]
Hello. We considered publishing the balance with every leaf, but there are significant privacy-related tradeoffs with that approach. [Bitmex ](https://blog.bitmex.com/addressing-the-privacy-gap-in-proof-of-liability-protocols/) published a fantastic article that unpacks how Coinfloor leaked critical intelligence about their customer balances by doing exactly that. You could view their largest client balances and make accurate assumptions about their identities. You could also map clients over multiple audits if their balances did not change.

There are three ways to solve this. 
1. Do a ZK-snarks [proof ](https://vitalik.ca/general/2022/11/19/proof_of_solvency.html) which would preserve privacy. This is arguably the best approach, but [we ](https://www.silversixpence.io/) are still building this capability
2. Break up every user's balances in a random number smaller than _n_ Merkle leafs and publish the entire leaf node layer. This would allow anyone to check for negative balances and enable exponential privacy improvements to the approach by Coinfloor. It would however come at the expense of the user experience in verifying the Proof, as you would have to search for multiple leafs
3. Introduce a trust vector. An independent, trusted third party is introduced to manually check the liabilities dataset for negative balances. We (Silver Sixpence) followed a procedure to check this and a range of other things like duplicate customer IDs and row counts.
