### ISSUE TITLE
6e2ee6e4e0ae6dda90b09c7c9e262766c7b894994e6f13cdde8c6bb5155bd53e

### ISSUE THREAD

**Issue by robert816** [silversixpence-crypto/merkletree-verify#22]

**Comment by FUIMUS7** [comment]
I have some questions about my accounts, and my wallets.. . #1 i did see you on this as well; maybe you can assist please. How can we get a get in touch? Thanks!

**Comment by jgabarda** [comment]
You have to verrify your merkletree to your binance wallet

**Comment by robert816** [comment]
``https://github.com/sponsors/explore?account=RPG-Technological

**Comment by robert816** [comment]
``
