### ISSUE TITLE
Merkle tree

### ISSUE THREAD

**Issue by Maca001** [silversixpence-crypto/merkletree-verify#3]
SilverSixpence Merkle Tree
Toggle navigation
Binance underwent a Proot-of-Reserves and Proof-of-Liabilities review at 22 Nov 2022 23:59:59 UTC when a snapshot of their total reserves and liabilities were taken to determine the total collagenization ratio of their asset holdings.

This page allows users of Binance to independently verify that their assets were included in the total liabilities calculation through a Merkle-proof.

Download Report
Search your merkle leaf

Use the search field above to search for your merkle proof.

Search
Your merkle proof will be displayed here.

Calculate your merkle leaf

Paste your Merkle Hash in the input and click "Calculate". This will produce your Merkle Leaf Node.

Verify your tree nodes

Copy both node hashes into the text field below and calculate the node one level higher up to the root.

Calculate

Calculate
Merle Root Hash

A Merkle Tree data structure is used to consolidate all client account information into a single root hash, known as a Merkle Root. The Merkle Root was compiled by hashing all client accounts into a single output. The Merkle Root for Binance review PR22NOV22 is b47221413078d47b0d9beb40447786904dae1ed2ff35e365416b5de6cd1089ee.

Want to do the verification yourself? Have a look at the open source verification code and readme on Github

**Comment by Bbjj88h** [comment]
> SilverSixpence Merkle Tree
> Toggle navigation
> Binance underwent a Proot-of-Reserves and Proof-of-Liabilities review at 22 Nov 2022 23:59:59 UTC when a snapshot of their total reserves and liabilities were taken to determine the total collagenization ratio of their asset holdings.
> 
> This page allows users of Binance to independently verify that their assets were included in the total liabilities calculation through a Merkle-proof.
> 
> Download Report
> Search your merkle leaf
> 
> Use the search field above to search for your merkle proof.
> 
> 
> Search
> Your merkle proof will be displayed here.
> 
> Calculate your merkle leaf
> 
> Paste your Merkle Hash in the input and click "Calculate". This will produce your Merkle Leaf Node.
> 
> Verify your tree nodes
> 
> Copy both node hashes into the text field below and calculate the node one level higher up to the root.
> 
> 
> 
> 
> 
> Calculate
> 
> Calculate
> Merle Root Hash
> 
> A Merkle Tree data structure is used to consolidate all client account information into a single root hash, known as a Merkle Root. The Merkle Root was compiled by hashing all client accounts into a single output. The Merkle Root for Binance review PR22NOV22 is b47221413078d47b0d9beb40447786904dae1ed2ff35e365416b5de6cd1089ee.
> 
> 
> Want to do the verification yourself? Have a look at the open source verification code and readme on Github

b47221413078d47b0d9beb40447786904dae1ed2ff35e365416b5de6cd1089ee
