### ISSUE TITLE
Merkletree

### ISSUE THREAD

**Issue by ELWi81** [silversixpence-crypto/merkletree-verify#32]

**Comment by Atok66** [comment]
Y no discription provide.
1.not enough or not right info from me
2. or i deal with investment project totally control by system whether you cannot penetrated?
3.or I deal with un LEGIT platform?

**Comment by CrytoCraze77** [comment]
I have no idea wtf this mean anything do crypto it’s god damn lying stealing sob!Sent from my iPhoneOn Jun 6, 2023, at 11:03, ELWi81 ***@***.***> wrote:﻿

**Comment by Atok66** [comment]
To me that consider close case.but if you steel asking about that matter.i
need to know why i newer register with metamask but my domain with them.

**Comment by Drmiller85** [comment]
#37

**Comment by Atok66** [comment]
Hello sir.actually i got few emails within my crypto exercise.maybe
sometimes i am wrong to put my right emails.thats maybe somestimes yours
systems refused to veryfied my registration.and all my emails is validated
emails and was approved 2nd step veryfication from Google.tq you sir.
