### ISSUE TITLE
Silversixprnce-crypto/merkletree-verify/k0p01il-verifying_BNB-merk-tree: "b47221413078d47b0d9beb40447786904 dae1ed2ff35e365416b5de6cd1089ee"

### ISSUE THREAD

**Issue by K0P01IL** [silversixpence-crypto/merkletree-verify#6]

**Comment by K0P01IL** [comment]
My merkle tree for Binance verification.

**Comment by Bbjj88h** [comment]
Run

**Comment by Atok66** [comment]
Tq sir for your email.for your information my account with binance is
consider over.because all that assets now should be with coinbase.this
think happened because I changed my wallet at my principal platform.🙏🙏🙏
